# db
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot
    username: root
    password: "!qkr0147258"
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    include: oauth

# mybatis
mybatis:
  mapper-locations: classpath:/sql/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

